import asyncio
import json
import logging
from typing import List, AsyncGenerator

from geenii.ai import generate_chat_completion
from geenii.chat.chat_bots import BotInterface
from geenii.chat.chat_models import ToolCallResultContent, ContentPart, TextContent
from geenii.config import DEFAULT_COMPLETION_MODEL
from geenii.datamodels import ModelMessage
from geenii.skills import SkillRegistry
from geenii.tools import execute_tool_call, ToolRegistry
from geenii.tts import tts_say_cli

logger = logging.getLogger(__name__)

DEFAULT_WIZARD_SYSTEM_PROMPT = """
You are an AI assistant that MUST use available tools when they are relevant.

CORE RULES:

1. NEVER answer from internal knowledge if a tool exists that can provide up-to-date, factual, or external information.
2. ALWAYS evaluate whether a tool should be used BEFORE generating a final response.
3. If a suitable tool exists, you MUST call the tool instead of answering directly.
4. Only produce a final natural-language answer AFTER tool results are returned.
5. Follow the tool calling format EXACTLY.

DECISION PROCESS:

Step 1 — Analyze user intent.
Step 2 — Check available tools.
Step 3 — If any tool can help, return a tool call with the appropriate arguments.
Step 4 — If no tools are relevant, answer the user's question directly.
"""


def message_to_prompt(message: str | list[ContentPart]) -> str:
    if isinstance(message, str):
        return message
    elif isinstance(message, list):
        return " ".join([content.to_text() for content in message])
    else:
        raise ValueError("Unsupported message format")


# class BaseWizardStep:
#     """
#     Base class for a wizard step. A step represents a single action or decision point in the wizard's process.
#     """
#
#     async def run(self) -> AsyncGenerator[ContentPart, None]:
#         """
#         The __aiter__ method allows the step to be used as an asynchronous generator that yields ContentPart objects.
#         This can be used to generate intermediate content parts as the step is executed.
#         """
#         yield TextContent(text="BaseWizardStep: Not implemented")
#
# class AnonymousStep:
#     name: str
#     callable: Callable[[ModelMessage], AsyncGenerator[ContentPart, None]]
#
#     async def run(self) -> AsyncGenerator[ContentPart, None]:
#         return self.callable(ModelMessage(role="assistant", content=[]))


class Wizard(BotInterface):

    def __init__(self, name, model: str = None, system_prompt: str = None, description: str = None,
                 tools: set[str] = None, tool_registry: ToolRegistry = None,
                 skills: set[str] = None, skill_registry: SkillRegistry = None,
                 mcp_servers: dict[str, str] = None):

        self.name = name
        self.description = description
        self.model = model or DEFAULT_COMPLETION_MODEL
        self.system_prompt = system_prompt or DEFAULT_WIZARD_SYSTEM_PROMPT
        self.tools = tools or set()
        self.mcp_servers = {}
        #self.skills = skills or set()
        self.message_history: List[ModelMessage] = []

        self._tool_registry = tool_registry or ToolRegistry()
        self._skill_registry = skill_registry or SkillRegistry()

        self._queue: asyncio.Queue[dict] = asyncio.Queue()

    async def prompt(self, message: str | list[ContentPart]) -> AsyncGenerator[ModelMessage, None]:
        """Process an incoming message and generate a response by enqueuing tasks to the internal queue and processing them sequentially."""
        # enqueue new llm task
        await self._queue.put({"task": "ask_llm", "arguments": {"message": message}})
        # process the queue and yield messages
        async for msg in self._process_queue():
            yield msg

    async def _process_queue(self) -> AsyncGenerator[ModelMessage, None]:
        """Process tasks from the internal queue sequentially. Yields content parts generated by the tasks. Exits when the queue is empty."""
        i = 0
        while self._queue.qsize() > 0:
            task = await self._queue.get()
            i += 1
            logger.info(f"Task #{i}")
            try:
                if task["task"] == "ask_llm":
                    async for msg in self._ask_llm(**task["arguments"]):
                        yield msg
                else:
                    logger.critical(f"Unknown task type: {task['task']}")
            except Exception as e:
                logger.exception(f"Error processing task {task['task']}: {str(e)}", exc_info=e)
                # todo handle exceptions properly, e.g. by yielding an error message
            finally:
                self._queue.task_done()

    async def _ask_llm(self, message: str | list[ContentPart]) -> AsyncGenerator[ModelMessage, None]:
        """Generate LLM chat completion response in the current context. Handles tool calls"""
        full_system_prompt = self.build_system_prompt()
        tool_names = self.tools
        prompt = message_to_prompt(message)

        # run sync task in thread pool to avoid blocking the event loop while waiting for the response
        def generate_response():
            return generate_chat_completion(prompt=prompt,
                                            model=self.model,
                                            system=full_system_prompt,
                                            messages=self.message_history,
                                            tools=tool_names,
                                            tool_registry=self._tool_registry,
                                            # temperature=temperature,
                                            # output_format=output_format
                                            )

        response = await asyncio.to_thread(generate_response)
        logger.info(f"Received model response for prompt '{prompt}' with {len(response.output)} content parts.")

        tool_calls = 0
        output_parts: List[ContentPart] = []
        for item in response.output:
            if item.type == "text":
                logger.info(">>" + item.text)
                output_parts.append(TextContent(text=item.text))
            elif item.type == "tool_call":
                tool_call_id = item.call_id
                try:
                    # execute the tool call and get the result
                    logger.info(f">> Tool call: {item.name} with args {item.arguments}")
                    tool_usage_approved = await self.request_tool_execution(tool_name=item.name, arguments=item.arguments, call_id=tool_call_id)
                    if tool_usage_approved:
                        logger.info(f">> Tool usage approved: {item.name}")
                        tool_result = execute_tool_call(self._tool_registry, item.name, **item.arguments)
                        print(f"Tool result", tool_result)
                        output_parts.append(ToolCallResultContent(name=item.name, argument=item.arguments, call_id=tool_call_id, result=tool_result))
                        tool_calls += 1
                    else:
                        logger.critical(f"Tool execution for {item.name} was rejected by the request_tool_execution method.")
                        output_parts.append(ToolCallResultContent(name=item.name, argument=item.arguments, call_id=tool_call_id,
                                                                  result={"error": "Tool execution rejected."}))

                    # remove the tool from the list of available tools for the next iteration to prevent infinite loops
                    if item.name in tool_names:
                        tool_names.remove(item.name)

                except Exception as e:
                    logger.exception(f"Error executing tool {item.name}", exc_info=e)
                    # print stack trace
                    #import traceback
                    #traceback.print_exc()

                    output_parts.append(ToolCallResultContent(name=item.name, argument=item.arguments, call_id=tool_call_id, result={"error": str(e)}))
                    raise e
            else:
                logger.warning(f"Unknown content part type: {item.type}")
                output_parts.append(TextContent(text=f"[Unknown content type: {item.type}]"))

        # add user request to message history
        input_message = ModelMessage(role="user", content=[TextContent(text=prompt)])
        self.message_history.append(input_message)
        #yield input_message

        # add model response to message history
        output_message = ModelMessage(role="assistant", content=output_parts)
        self.message_history.append(output_message)

        # yield the output message
        yield output_message


    async def request_tool_execution(self, tool_name: str, arguments: dict, call_id: str) -> bool:
        """
        This method can be overridden to implement custom logic for approving or rejecting tool execution requests.
        By default, it approves all tool execution requests.
        """
        return True

    def build_system_prompt(self) -> str:
        """
        Build the full system prompt for the wizard, including the base system prompt and any additional information from loaded skills.
        """
        skills_prompt = self.build_skills_prompt()
        full_system_prompt = self.system_prompt + "\n\n" + skills_prompt
        return full_system_prompt

    def build_skills_prompt(self) -> str:
        """
        Returns a combined prompt for all loaded skills that can be included in the system prompt
        to provide the wizard with information about its skills and how to use them.
        :return:
        """
        skills_prompt = ""
        for skill_name in self._skill_registry.list_skills():
            skill = self._skill_registry.get_skill(skill_name)
            if skill:
                skills_prompt += f"You have a special skill named {skill_name}:\n"
                skills_prompt += f"{skill.description}\n"
                skills_prompt += f"Instructions for {skill_name} are following:\n{skill.instructions}\n\n"
        return skills_prompt

    def load_skill(self, skill_name: str):
        """
        Load a skill by name and add its tools to the wizard's available tools.
        This is a placeholder method and should be implemented to load actual skills and their tools.
        """
        logger.info(f"Loading skill: {skill_name}")
        self._skill_registry.load_skill(skill_name)

    def unload_skill(self, skill_name: str):
        """
        Unload a skill by name.
        """
        logger.info(f"Unloading skill: {skill_name}")
        self._skill_registry.unload_skill(skill_name)


class CliWizard(Wizard):

    async def request_tool_execution(self, tool_name: str, arguments: dict, call_id: int) -> bool:
        asyncio.create_task(asyncio.to_thread(tts_say_cli(f"A tool call was requested: {tool_name} with {len(arguments)} arguments. Do you approve?")))

        user_input = input(f"Tool '{tool_name}' wants to execute with arguments {arguments}. Approve? (y/n): ")
        return user_input.lower() == 'y'


def load_wizard_from_json(file_path: str) -> Wizard:
    """
    Load a wizard configuration from a JSON file and create a Wizard instance.
    The JSON file should contain the following fields:
    - name: The name of the wizard
    - model: (optional) The AI model to use for this wizard
    - system: (optional) The system prompt to use for this wizard
    - description: (optional) A description of the wizard's purpose and capabilities
    - tools: (optional) A list of tool definitions that the wizard can use
    - mcp_servers: (optional) A dictionary of MCP server configurations that the wizard can connect to
    """

    with open(file_path, 'r') as f:
        config = json.load(f)

    name = config.get("name")
    model = config.get("model")
    system = config.get("system")
    description = config.get("description")
    tools = config.get("tools", [])
    mcp_servers = config.get("mcp_servers", {})

    if not name:
        raise ValueError("Wizard configuration must include a 'name' field.")

    wizard = Wizard(name=name, model=model, system_prompt=system, description=description,
                    tools=tools, mcp_servers=mcp_servers)
    return wizard


# def load_wizards_from_directory(directory_path: str) -> List[Wizard]:
#     """
#     Load all wizard configurations from JSON files in the specified directory and create a list of Wizard instances.
#     """
#     import os
#
#     wizards = []
#     for filename in os.listdir(directory_path):
#         if filename.endswith(".wizard.json"):
#             file_path = os.path.join(directory_path, filename)
#             try:
#                 wizard = load_wizard_from_json(file_path)
#                 wizards.append(wizard)
#                 print(f"Loaded wizard: {wizard.name}")
#             except Exception as e:
#                 print(f"Error loading wizard from {file_path}: {e}")
#
#     return wizards
