
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile-localserver
    ports:
      - "33311:33311"
    networks:
      - geenii-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data
      - "$HOME/.geenii:/home/geenii/.geenii"
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
    env_file:
      - "$HOME/.geenii/.env"
