import abc
import asyncio
from typing import Set, List, AsyncGenerator
import logging

from geenii.agent.base import DEFAULT_AGENT_SYSTEM_PROMPT, BaseTask
from geenii.chat.chat_bots import BotInterface
from geenii.chat.chat_models import ContentPart, TextContent
from geenii.config import DEFAULT_COMPLETION_MODEL
from geenii.datamodels import ModelMessage
from geenii.hidl import HumanInTheLoopController, NoHumanInTheLoopController
from geenii.memory import ChatMemory
from geenii.skills import SkillRegistry
from geenii.tool.registry import ToolRegistry
from geenii.tools import init_builtin_tools, init_mcp_server_tools

logger = logging.getLogger(__name__)

class BaseAgent(BotInterface, abc.ABC):
    MAX_TASKS = 10  # maximum number of tasks to process in the queue to prevent infinite loops

    def __init__(self, name, model: str = None, system_prompt: str = None, description: str = None,
                 tool_registry: ToolRegistry = None, skill_registry: SkillRegistry = None,
                 allowed_tools: Set[str] = None,
                 context_id: str = None, memory: ChatMemory = None, hidl: HumanInTheLoopController = None):

        self.name = name
        self.description = description
        self.model = model or DEFAULT_COMPLETION_MODEL
        self.system_prompt = system_prompt or DEFAULT_AGENT_SYSTEM_PROMPT
        self.message_history: List[ModelMessage] = []
        self.memory = memory or None
        self.context_id = context_id or None
        self.allowed_tools: Set[str] = allowed_tools or set()
        self.selected_skill: str | None = None

        self._tool_registry = tool_registry or ToolRegistry()
        self._skill_registry = skill_registry or SkillRegistry()
        self._tasks: asyncio.Queue[BaseTask] = asyncio.Queue()
        self._hidl = hidl or NoHumanInTheLoopController()
        self._initialized = False

    def __repr__(self):
        return f"Agent(name={self.name}, context_id={self.context_id}, model={self.model}, tools={self.allowed_tools}, skills={self.skills.names()})"

    @property
    def tools(self) -> ToolRegistry:
        return self._tool_registry

    @property
    def skills(self) -> SkillRegistry:
        return self._skill_registry

    async def _initialize(self):
        """Initialize the agent by loading built-in tools, MCP server tools, and any tools from loaded skills."""
        if self._initialized:
            return

        init_builtin_tools(self._tool_registry)
        await init_mcp_server_tools(self._tool_registry)
        self._initialized = True

    async def enqueue_task(self, task: BaseTask):
        """Enqueue a task to be processed by the agent."""
        await self._tasks.put(task)

    async def prompt(self, message: str | list[ContentPart]) -> AsyncGenerator[ModelMessage, None]:
        """Process an incoming message and generate a response by enqueuing tasks to the internal queue and processing them sequentially."""
        # enqueue new llm task
        # await self._tasks.put(LLMTask(self, message=message))
        # await self._tasks.put(FindBestAgentTask(self, prompt=message_to_prompt(message)))
        await self._initialize()
        await self._handle_prompt(message)

        # process the queue and yield messages
        async for msg in self._process_queue():
            yield msg

    @abc.abstractmethod
    async def _handle_prompt(self, message: str | list[ContentPart]):
        """Handle an incoming prompt message by enqueuing an LLM task to generate a response."""
        # await self.enqueue_task(LLMTask(self, message=message))
        ...

    async def _process_queue(self) -> AsyncGenerator[ModelMessage, None]:
        """
        Process tasks from the internal queue sequentially.
        Yields content parts generated by the tasks.
        Exits when the queue is empty.
        """
        i = 0
        while self._tasks.qsize() > 0 and i < self.MAX_TASKS:
            task = await self._tasks.get()
            i += 1
            logger.info(f"Task #{i} {task.__class__.__name__} started. Queue size: {self._tasks.qsize()}")
            try:
                if isinstance(task, BaseTask):
                    async for result in task.execute():
                        # parse task results
                        if result is None:
                            continue
                        if isinstance(result, ModelMessage):
                            yield result
                        elif isinstance(result, BaseTask):
                            # if the task yields another task, we enqueue it
                            await self.enqueue_task(result)
                            continue
                        else:
                            logger.critical(f"Task {task} yielded an invalid message of type {type(result)}: {result}")
                            raise ValueError(f"Unsupported task response type: {type(result)}")
                else:
                    logger.critical(f"Unsupported task type: {type(task)}")
                    raise ValueError(f"Unsupported task type: {type(task)}")
            except Exception as e:
                logger.exception(f"Error processing task {task.__class__.__name__}: {str(e)}", exc_info=e)
                # todo handle exceptions properly, e.g. by yielding an error message
                yield ModelMessage(role="assistant",
                                   content=[TextContent(text=f"An error occurred while processing the task: {str(e)}")])
            finally:
                self._tasks.task_done()

    async def request_tool_execution(self, tool_name: str, arguments: dict, call_id: str) -> bool:
        """
        This method can be overridden to implement custom logic for approving or rejecting tool execution requests.
        By default, it approves all tool execution requests.
        """
        if self._hidl:
            return await self._hidl.request_tool_execution(tool_name, arguments, call_id)
        return True

    def load_skill(self, skill_name: str):
        """
        Load a skill by name and add its tools to the agent's available tools.
        """
        logger.warning(f"Using deprecated method Agent.load_skill(). Use 'Agent.skills.load({skill_name})' instead.")
        self.skills.load(skill_name)

    def unload_skill(self, skill_name: str):
        """
        Unload a skill by name.
        """
        logger.warning(
            f"Using deprecated method Agent.unload_skill(). Use 'Agent.skills.unload({skill_name})' instead.")
        self.skills.unload(skill_name)
